export const FETCH_TASKS_REQUEST = 'FETCH_TASKS_REQUEST';
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS';
export const FETCH_TASKS_FAILURE = 'FETCH_TASKS_FAILURE';

export const POST_TASKS_REQUEST = 'POST_TASKS_REQUEST';
export const POST_TASKS_SUCCESS = 'POST_TASKS_SUCCESS';
export const POST_TASKS_FAILURE = 'POST_TASKS_FAILURE';

export const TOOGLE_REVERSE_ORDER = 'TOOGLE_REVERSE_ORDER';